use std::collections::BTreeMap;

use super::super::super::AppState;

pub(crate) fn redacted_config_snapshot(state: &AppState) -> BTreeMap<String, serde_json::Value> {
    let mut out = BTreeMap::new();
    out.insert(
        "app_env".to_string(),
        serde_json::json!(state.config.app_env),
    );
    out.insert(
        "app_host".to_string(),
        serde_json::json!(state.config.app_host),
    );
    out.insert(
        "app_port".to_string(),
        serde_json::json!(state.config.app_port),
    );
    out.insert(
        "session_cookie_name".to_string(),
        serde_json::json!(state.config.session_cookie_name),
    );
    out.insert(
        "session_cookie_domain".to_string(),
        serde_json::json!(state.config.session_cookie_domain),
    );
    out.insert(
        "session_ttl_seconds".to_string(),
        serde_json::json!(state.config.session_ttl_seconds),
    );
    out.insert(
        "step_up_ttl_seconds".to_string(),
        serde_json::json!(state.config.step_up_ttl_seconds),
    );
    out.insert(
        "user_app_host".to_string(),
        serde_json::json!(state.config.user_app_host),
    );
    out.insert(
        "admin_app_host".to_string(),
        serde_json::json!(state.config.admin_app_host),
    );
    out.insert(
        "passkey_provider".to_string(),
        serde_json::json!(state.config.passkey.provider),
    );
    out.insert(
        "webauthn_rp_id".to_string(),
        serde_json::json!(state.config.passkey.webauthn_rp_id),
    );
    out.insert(
        "webauthn_rp_origin".to_string(),
        serde_json::json!(state.config.passkey.webauthn_rp_origin),
    );
    out.insert(
        "database_url_present".to_string(),
        serde_json::json!(!state.config.database_url.trim().is_empty()),
    );
    out.insert(
        "redis_url_present".to_string(),
        serde_json::json!(!state.config.redis.url.trim().is_empty()),
    );
    out.insert(
        "session_secret_present".to_string(),
        serde_json::json!(!state.config.session_secret.trim().is_empty()),
    );
    out.insert(
        "invite_base_url".to_string(),
        serde_json::json!(state.config.invite_base_url),
    );
    out
}
