#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_DIR="${REPO_ROOT}/runtime"
FRONTEND_DIR="${RUNTIME_DIR}/frontend"
MIGRATIONS_DIR="${RUNTIME_DIR}/migrations"
POSTGRES_ENV_FILE="${REPO_ROOT}/env/dev/postgres.env"
DEV_RUNTIME_ENV_FILE="${REPO_ROOT}/env/dev/runtime.env"
LOCAL_ENV_FILE="${REPO_ROOT}/env/local/runtime.env"

POSTGRES_CONTAINER="${BOMINAL_POSTGRES_CONTAINER:-bominal-postgres}"
REDIS_CONTAINER="${BOMINAL_REDIS_CONTAINER:-bominal-redis}"
POSTGRES_IMAGE="${BOMINAL_POSTGRES_IMAGE:-postgres:16-alpine}"
REDIS_IMAGE="${BOMINAL_REDIS_IMAGE:-redis:7-alpine}"
POSTGRES_PORT="${BOMINAL_POSTGRES_PORT:-55432}"
REDIS_PORT="${BOMINAL_REDIS_PORT:-6379}"
RUN_TESTS="${BOMINAL_RUN_TESTS:-1}"
RUN_MIGRATIONS="${BOMINAL_RUN_MIGRATIONS:-1}"

log() {
  printf '[bootstrap-local] %s\n' "$*"
}

require_cmd() {
  local cmd="$1"
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "missing required command: ${cmd}" >&2
    exit 1
  fi
}

container_exists() {
  local container_name="$1"
  docker ps -aq -f "name=^/${container_name}$" | grep -q .
}

container_running() {
  local container_name="$1"
  docker ps -q -f "name=^/${container_name}$" | grep -q .
}

container_port_binding() {
  local container_name="$1"
  local container_port="$2"
  docker inspect -f "{{with index .NetworkSettings.Ports \"${container_port}\"}}{{(index . 0).HostPort}}{{end}}" "${container_name}" 2>/dev/null || true
}

start_postgres() {
  local existing_port
  if container_exists "${POSTGRES_CONTAINER}"; then
    existing_port="$(container_port_binding "${POSTGRES_CONTAINER}" "5432/tcp")"
    if [ -n "${existing_port}" ] && [ "${existing_port}" != "${POSTGRES_PORT}" ]; then
      log "postgres container port mismatch (have ${existing_port}, want ${POSTGRES_PORT}); recreating container"
      docker rm -f "${POSTGRES_CONTAINER}" >/dev/null
    fi
  fi

  if container_running "${POSTGRES_CONTAINER}"; then
    log "postgres container already running: ${POSTGRES_CONTAINER}"
    return
  fi

  if container_exists "${POSTGRES_CONTAINER}"; then
    log "starting existing postgres container: ${POSTGRES_CONTAINER}"
    docker start "${POSTGRES_CONTAINER}" >/dev/null
    return
  fi

  log "creating postgres container: ${POSTGRES_CONTAINER}"
  docker run -d \
    --name "${POSTGRES_CONTAINER}" \
    -p "${POSTGRES_PORT}:5432" \
    --env-file "${POSTGRES_ENV_FILE}" \
    -v "${POSTGRES_CONTAINER}-data:/var/lib/postgresql/data" \
    "${POSTGRES_IMAGE}" >/dev/null
}

start_redis() {
  if container_running "${REDIS_CONTAINER}"; then
    log "redis container already running: ${REDIS_CONTAINER}"
    return
  fi

  if container_exists "${REDIS_CONTAINER}"; then
    log "starting existing redis container: ${REDIS_CONTAINER}"
    docker start "${REDIS_CONTAINER}" >/dev/null
    return
  fi

  log "creating redis container: ${REDIS_CONTAINER}"
  docker run -d \
    --name "${REDIS_CONTAINER}" \
    -p "${REDIS_PORT}:6379" \
    -v "${REDIS_CONTAINER}-data:/data" \
    "${REDIS_IMAGE}" \
    redis-server --appendonly yes >/dev/null
}

wait_for_postgres() {
  local attempts=30
  local try=1

  while [ "${try}" -le "${attempts}" ]; do
    if docker exec "${POSTGRES_CONTAINER}" pg_isready \
      -U "${POSTGRES_USER}" \
      -d "${POSTGRES_DB}" >/dev/null 2>&1; then
      log "postgres is ready"
      return
    fi
    sleep 1
    try=$((try + 1))
  done

  echo "postgres readiness check failed after ${attempts}s" >&2
  exit 1
}

wait_for_redis() {
  local attempts=30
  local try=1

  while [ "${try}" -le "${attempts}" ]; do
    if [ "$(docker exec "${REDIS_CONTAINER}" redis-cli ping 2>/dev/null || true)" = "PONG" ]; then
      log "redis is ready"
      return
    fi
    sleep 1
    try=$((try + 1))
  done

  echo "redis readiness check failed after ${attempts}s" >&2
  exit 1
}

apply_migrations() {
  if [ ! -d "${MIGRATIONS_DIR}" ]; then
    log "no migrations directory found; skipping migration step"
    return
  fi

  log "applying runtime SQL migrations"
  local applied=0
  while IFS= read -r migration; do
    applied=$((applied + 1))
    log "migration ${applied}: $(basename "${migration}")"
    docker exec -i "${POSTGRES_CONTAINER}" psql \
      -v ON_ERROR_STOP=1 \
      -U "${POSTGRES_USER}" \
      -d "${POSTGRES_DB}" < "${migration}" >/dev/null
  done < <(find "${MIGRATIONS_DIR}" -maxdepth 1 -type f -name '*.sql' | sort)
}

ensure_local_env() {
  mkdir -p "$(dirname "${LOCAL_ENV_FILE}")"

  if [ -f "${LOCAL_ENV_FILE}" ]; then
    if grep -q "generated by scripts/bootstrap-local.sh" "${LOCAL_ENV_FILE}"; then
      set_env_key "${LOCAL_ENV_FILE}" "DATABASE_URL" "postgresql+asyncpg://bominal:bominal@127.0.0.1:${POSTGRES_PORT}/bominal"
      set_env_key "${LOCAL_ENV_FILE}" "REDIS_URL" "redis://127.0.0.1:${REDIS_PORT}/0"
      set_env_key "${LOCAL_ENV_FILE}" "FRONTEND_ASSETS_DIR" "${FRONTEND_DIR}/dist"
      log "synced generated local override: ${LOCAL_ENV_FILE}"
    else
      log "local override exists: ${LOCAL_ENV_FILE} (left unchanged)"
    fi
    return
  fi

  cat > "${LOCAL_ENV_FILE}" <<EOF
# Local-only runtime overrides generated by scripts/bootstrap-local.sh
DATABASE_URL=postgresql+asyncpg://bominal:bominal@127.0.0.1:${POSTGRES_PORT}/bominal
REDIS_URL=redis://127.0.0.1:${REDIS_PORT}/0
FRONTEND_ASSETS_DIR=${FRONTEND_DIR}/dist
EOF
  log "created local override: ${LOCAL_ENV_FILE}"
}

set_env_key() {
  local file="$1"
  local key="$2"
  local value="$3"

  if grep -q "^${key}=" "${file}"; then
    sed -i.bak "s|^${key}=.*|${key}=${value}|" "${file}"
    rm -f "${file}.bak"
  else
    printf '%s=%s\n' "${key}" "${value}" >> "${file}"
  fi
}

load_postgres_env() {
  if [ ! -f "${POSTGRES_ENV_FILE}" ]; then
    echo "missing postgres env file: ${POSTGRES_ENV_FILE}" >&2
    exit 1
  fi

  # shellcheck disable=SC1090
  set -a
  source "${POSTGRES_ENV_FILE}"
  set +a
}

load_runtime_env_for_checks() {
  if [ ! -f "${DEV_RUNTIME_ENV_FILE}" ]; then
    echo "missing runtime env file: ${DEV_RUNTIME_ENV_FILE}" >&2
    exit 1
  fi

  set -a
  # shellcheck disable=SC1090
  source "${DEV_RUNTIME_ENV_FILE}"
  if [ -f "${LOCAL_ENV_FILE}" ]; then
    # shellcheck disable=SC1090
    source "${LOCAL_ENV_FILE}"
  fi
  set +a
}

escape_sql_literal() {
  printf "%s" "${1//\'/\'\'}"
}

ensure_postgres_contract() {
  local db_user="${POSTGRES_USER:-}"
  local db_name="${POSTGRES_DB:-}"
  local db_password="${POSTGRES_PASSWORD:-}"

  if [ -z "${db_user}" ] || [ -z "${db_name}" ]; then
    echo "POSTGRES_USER and POSTGRES_DB must be set in ${POSTGRES_ENV_FILE}" >&2
    exit 1
  fi

  local db_user_sql
  local db_name_sql
  local db_password_sql
  local admin_role
  local fallback_admin_role="postgres"
  db_user_sql="$(escape_sql_literal "${db_user}")"
  db_name_sql="$(escape_sql_literal "${db_name}")"
  db_password_sql="$(escape_sql_literal "${db_password}")"
  admin_role="${POSTGRES_ADMIN_ROLE:-${db_user}}"

  log "ensuring postgres role/database contract (${db_user}/${db_name})"
  if ! docker exec -i "${POSTGRES_CONTAINER}" psql \
    -v ON_ERROR_STOP=1 \
    -U "${admin_role}" \
    -d postgres <<SQL >/dev/null
do \$\$
begin
  if not exists (select 1 from pg_roles where rolname = '${db_user_sql}') then
    create role "${db_user}" login password '${db_password_sql}';
  else
    alter role "${db_user}" login password '${db_password_sql}';
  end if;
end
\$\$;

do \$\$
begin
  if not exists (select 1 from pg_database where datname = '${db_name_sql}') then
    create database "${db_name}" owner "${db_user}";
  end if;
end
\$\$;
SQL
  then
    if [ "${admin_role}" = "${fallback_admin_role}" ]; then
      echo "failed to connect to postgres admin role '${admin_role}' in ${POSTGRES_CONTAINER}" >&2
      exit 1
    fi

    log "failed with admin role '${admin_role}', retrying with '${fallback_admin_role}'"
    docker exec -i "${POSTGRES_CONTAINER}" psql \
      -v ON_ERROR_STOP=1 \
      -U "${fallback_admin_role}" \
      -d postgres <<SQL >/dev/null
do \$\$
begin
  if not exists (select 1 from pg_roles where rolname = '${db_user_sql}') then
    create role "${db_user}" login password '${db_password_sql}';
  else
    alter role "${db_user}" login password '${db_password_sql}';
  end if;
end
\$\$;

do \$\$
begin
  if not exists (select 1 from pg_database where datname = '${db_name_sql}') then
    create database "${db_name}" owner "${db_user}";
  end if;
end
\$\$;
SQL
  fi

  docker exec -i "${POSTGRES_CONTAINER}" psql \
    -v ON_ERROR_STOP=1 \
    -U "${db_user}" \
    -d "${db_name}" <<SQL >/dev/null
grant all privileges on database "${db_name}" to "${db_user}";
grant all privileges on schema public to "${db_user}";
alter schema public owner to "${db_user}";
SQL
}

build_frontend_assets() {
  log "installing frontend dependencies"
  npm ci --prefix "${FRONTEND_DIR}"

  log "building frontend css"
  npm --prefix "${FRONTEND_DIR}" run build:css
}

run_runtime_tests() {
  log "running runtime test gate"
  (cd "${RUNTIME_DIR}" && cargo test --workspace --locked)
}

main() {
  require_cmd docker
  require_cmd npm
  require_cmd cargo

  if ! docker info >/dev/null 2>&1; then
    echo "docker daemon is not reachable; start docker and retry" >&2
    exit 1
  fi

  load_postgres_env
  ensure_local_env
  load_runtime_env_for_checks
  start_postgres
  start_redis
  wait_for_postgres
  wait_for_redis
  ensure_postgres_contract
  build_frontend_assets

  if [ "${RUN_MIGRATIONS}" = "1" ]; then
    apply_migrations
  else
    log "skipping migrations because BOMINAL_RUN_MIGRATIONS=${RUN_MIGRATIONS}"
  fi

  if [ "${RUN_TESTS}" = "1" ]; then
    run_runtime_tests
  else
    log "skipping runtime tests because BOMINAL_RUN_TESTS=${RUN_TESTS}"
  fi

  cat <<EOF

Local bootstrap complete.

To run API:
  cd runtime
  set -a
  source ../env/dev/runtime.env
  [ -f ../env/local/runtime.env ] && source ../env/local/runtime.env
  set +a
  cargo run -p bominal-api

To run worker:
  cd runtime
  set -a
  source ../env/dev/runtime.env
  [ -f ../env/local/runtime.env ] && source ../env/local/runtime.env
  set +a
  cargo run -p bominal-worker
EOF
}

main "$@"
