FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    git \
    python3 \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

COPY package.json package-lock.json ./
RUN npm ci

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
